url: "https://rogerkirkness.com"
permalink: /:title
plugins:
  - jekyll-sitemap
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      pdf: true
pdf:
  cache: false
  page_size: Digest
  layout: pdf
